name: Build container development images
on:
  push:
    branches:
      - 'hyogo-develop'

permissions:
  contents: read
  packages: write

jobs:
  build-image:
    uses: ./.github/workflows/build-container-image.yml
    with:
      platforms: linux/amd64
      use_native_arm64_builder: true
      push_to_images: |
        pinfort/mastodon
        ghcr.io/pinfort/mastodon
      # Only tag with latest when ran against the latest stable branch
      # This needs to be updated after each minor version release
      flavor: |
        latest=false
      tags: |
        type=raw,value=development
    secrets: inherit
