name: Build container release images
on:
  push:
    branches:
      - 'hyogo-master'

permissions:
  contents: read
  packages: write

jobs:
  build-image:
    uses: ./.github/workflows/build-container-image.yml
    with:
      platforms: linux/amd64
      use_native_arm64_builder: true
      push_to_images: |
        pinfort/mastodon
        ghcr.io/pinfort/mastodon
      # Do not use cache when building releases, so apt update is always ran and the release always contain the latest packages
      cache: false
      # Only tag with latest when ran against the latest stable branch
      # This needs to be updated after each minor version release
      flavor: |
        latest=auto
      tags: |
        type=raw,value=latest,enable={{is_default_branch}}
    secrets: inherit
