name: Build container release images
on:
  push:
    branches:
      - 'hyogo-master'

permissions:
  contents: read
  packages: write

jobs:
  build-image:
    uses: ./.github/workflows/build-container-image.yml
    with:
      platforms: linux/amd64
      use_native_arm64_builder: true
      push_to_images: |
        pinfort/mastodon
        ghcr.io/pinfort/mastodon
      # Only tag with latest when ran against the latest stable branch
      # This needs to be updated after each minor version release
      flavor: |
        latest=true
      tags: |
        type=pep440,pattern={{raw}}
        type=pep440,pattern=v{{major}}.{{minor}}
        type=raw,value=latest
    secrets: inherit
